// ==========================================================================
// 1. Currency Settings & Conversion Standards
// ==========================================================================
export const CURRENCIES = {
  USD: { symbol: '$', rate: 1.0 },
  EUR: { symbol: '€', rate: 0.92 },
  GBP: { symbol: '£', rate: 0.79 },
  JPY: { symbol: '¥', rate: 152.0 },
  SAR: { symbol: 'ر.س', rate: 3.75 }
};

// ==========================================================================
// 2. Multilingual Localization Engine
// ==========================================================================
export const TRANSLATIONS = {
  en: {
    tagline: "Personal Travel Planner",
    selectTrip: "Select Trip",
    navNewTrip: "Plan New Trip",
    labelTravelers: "Travelers",
    labelStay: "Recommended Stay",
    labelBudget: "Est. Daily Spending",
    labelNeighborhood: "Current District",
    tabItinerary: "Day-by-Day Itinerary",
    tabStays: "Recommended Stays",
    tabBudget: "Cost Estimates & Budget",
    tabCustomize: "Modify & Customize",
    tabPacking: "Packing Checklist",
    btnAdjustPace: "Adjust Pace",
    btnPrint: "Print / PDF",
    labelNeighborhoodCluster: "Geographic Neighborhood Cluster",
    transitOptimizedSubtext: "Activities grouped within 1.2km to minimize walking and transit time for families.",
    labelWeatherAdaptation: "Weather Adaptation Plan",
    customizePlanTitle: "Customize This Day",
    customizePlanSubtitle: "Swap activities, change dining, or access official booking links.",
    actionSwapActivity: "Swap Activity",
    actionSwapActivityDesc: "Explore curated alternative attractions in this district",
    actionChangeRestaurant: "Change Restaurant",
    actionChangeRestaurantDesc: "Choose family-friendly, vegetarian, or local spots",
    actionAdjustPace: "Adjust Day Pace",
    actionAdjustPaceDesc: "Switch between relaxed, balanced, or active pacing",
    actionBookingGuide: "Booking Guide & Links",
    actionBookingGuideDesc: "Official passes, transit cards, and direct reservations",
    staysHeaderTitle: "Recommended Places to Stay",
    staysHeaderSubtitle: "Curated accommodations tailored to your group size, traveler ages, accessibility needs, and budget preference.",
    filterBy: "Filter by:",
    filterAll: "All Recommendations",
    filterFamilySuites: "Family Suites",
    filterAccessible: "Wheelchair / Stroller Ready",
    filterCentral: "Transit Centric",
    budgetHeaderTitle: "Cost Estimates & Budget Planning",
    budgetHeaderSubtitle: "Clear cost breakdowns for accommodations, local food, entry admissions, and neighborhood transit.",
    budgetTierLabel: "Budget Tier:",
    totalEstTripCost: "Total Estimated Trip Cost",
    dailySpendAverage: "Average Daily Spend",
    perPersonEstimate: "Per Person Estimate",
    budgetStatus: "Budget Health",
    onTrack: "On Track",
    includesAllExpenses: "Includes lodging, dining, transit & tickets",
    perTravelerTotal: "All-inclusive per traveler estimate",
    alignedWithTier: "Aligned with your selected comfort tier",
    categoryBreakdownTitle: "Expense Category Breakdown",
    catLodging: "Lodging",
    catDining: "Local Dining",
    catTickets: "Attractions & Entry",
    catTransit: "Neighborhood Transit",
    dailyCostBreakdownTitle: "Daily Spending Breakdown",
    thDay: "Day",
    thNeighborhood: "Neighborhood Cluster",
    thMeals: "Meals & Street Food",
    thTickets: "Attractions & Entries",
    thTransit: "Transit",
    thDailyTotal: "Daily Total",
    customizeHeaderTitle: "TripCraft Customization Studio",
    customizeHeaderSubtitle: "Adapt the itinerary to your group's energy level and preferences.",
    paceControlTitle: "Pace & Rhythm Control",
    paceControlSubtitle: "Adjust activity density for maximum comfort.",
    paceRelaxedName: "🌿 Relaxed & Unhurried",
    paceRelaxedTag: "Families & Seniors",
    paceRelaxedDesc: "Late starts, max 2 main stops daily, and extra café breaks.",
    paceBalancedName: "⚖️ Balanced & Curated",
    paceBalancedTag: "Recommended",
    paceBalancedDesc: "Morning and afternoon exploring with flexible evenings.",
    pacePackedName: "⚡ Active & Dynamic",
    pacePackedTag: "Active Explorers",
    pacePackedDesc: "Early start, 4-5 major spots daily, and maximum sights.",
    btnApplyPace: "Apply Pace to Itinerary",
    swapConsoleTitle: "Swap Activities or Restaurants",
    swapConsoleSubtitle: "Select any time slot to view immediate local alternatives.",
    labelTargetDay: "Select Day to Modify",
    labelTimeSlot: "Select Time Slot",
    slotMorning: "Morning Activity",
    slotLunch: "Lunch & Local Dining",
    slotAfternoon: "Afternoon Activity",
    slotEvening: "Evening Walk & Dinner",
    labelCuratedAlternates: "Curated Alternatives:",
    bookingGuidanceTitle: "Official Booking Guide",
    bookingGuidanceSubtitle: "Avoid third-party markups with direct official links.",
    packingHeaderTitle: "Smart Packing Checklist",
    packingHeaderSubtitle: "Tailored to weather forecasts, traveler ages, and activities.",
    packed: "Packed",
    footerText: "Crafting personalized, weather-adaptive journeys worldwide.",
    footerLangSupport: "Multilingual • Family & Accessibility Focused",
    modalNewTripTitle: "Plan a New Personalized Journey",
    formLabelDestination: "Destination City & Country *",
    formLabelDuration: "Duration (Days) *",
    formSectionTravelers: "Who is traveling? (Group size & age breakdown)",
    formLabelAdults: "Adults (Ages 18-64)",
    formLabelChildren: "Children / Teens (0-17)",
    formLabelSeniors: "Seniors (Ages 65+)",
    formLabelTripType: "Type of Visit *",
    typeFamily: "Family Vacation (Child-friendly)",
    typeCulture: "Cultural & Historical Exploration",
    typeRelaxation: "Relaxation & Nature",
    typeCelebration: "Celebration & Honeymoon",
    typeAdventure: "Adventure & Hiking",
    formLabelBudgetPref: "Budget Preference *",
    budgetOptionEconomy: "Economy (Hostels, street food, public transit)",
    budgetOptionModerate: "Moderate / Comfort (Family hotels, local dining)",
    budgetOptionLuxury: "Luxury / Premium (5-star, fine dining, private transit)",
    formLabelStartDate: "Start Date",
    formLabelSpecialNotes: "Special Notes / Accessibility Needs",
    btnCancel: "Cancel",
    btnGeneratePlan: "Generate Complete Trip Plan",
    completed: "Completed",
    markCompleted: "Mark Done",
    btnSwap: "Swap",
    btnBook: "Booking Info",
    btnSelectThis: "Select This",
    perNight: "/ night",
    btnLogin: "Login",
    btnRegister: "Register"
  },
  ar: {
    tagline: "مساعد التخطيط الشخصي للرحلات",
    selectTrip: "اختر الرحلة",
    navNewTrip: "خطط لرحلة جديدة",
    labelTravelers: "المسافرون",
    labelStay: "الإقامة الموصى بها",
    labelBudget: "الإنفاق اليومي التقديري",
    labelNeighborhood: "الحي الحالي",
    tabItinerary: "جدول الأيام خطوة بخطوة",
    tabStays: "خيارات الإقامة الموصى بها",
    tabBudget: "تقديرات التكلفة والميزانية",
    tabCustomize: "التعديل والتخصيص",
    tabPacking: "قائمة الأمتعة",
    btnAdjustPace: "تعديل النمط",
    btnPrint: "طباعة / PDF",
    labelNeighborhoodCluster: "التجمع الجغرافي للحي",
    transitOptimizedSubtext: "تم تجميع الأنشطة في نطاق 1.2 كم لتقليل وقت التنقل والمشي للعائلات.",
    labelWeatherAdaptation: "خطة التكيف مع الطقس",
    customizePlanTitle: "تخصيص هذا اليوم",
    customizePlanSubtitle: "قم بتبديل الأنشطة، تغيير المطاعم، أو استعراض روابط الحجز المباشرة.",
    actionSwapActivity: "تبديل النشاط",
    actionSwapActivityDesc: "استكشف معالم بديلة ومختارة في نفس الحي",
    actionChangeRestaurant: "تغيير المطعم",
    actionChangeRestaurantDesc: "اختر مطاعم عائلية، خيارات نباتية، أو مأكولات محلية",
    actionAdjustPace: "تعديل وتيرة اليوم",
    actionAdjustPaceDesc: "اختر بين النمط الهادئ، المتوازن، أو النشط",
    actionBookingGuide: "دليل الحجز والروابط الرسمية",
    actionBookingGuideDesc: "بطاقات التنقل، التذاكر الرسمية، والحجوزات المباشرة",
    staysHeaderTitle: "أماكن الإقامة الموصى بها",
    staysHeaderSubtitle: "أماكن إقامة مختارة بعناية لتناسب حجم مجموعتك وأعمار المسافرين وسهولة الوصول وميزانيتك.",
    filterBy: "تصفية حسب:",
    filterAll: "جميع التوصيات",
    filterFamilySuites: "أجنحة عائلية",
    filterAccessible: "مناسب للعربات والكراسي المتحركة",
    filterCentral: "قريب من المواصلات",
    budgetHeaderTitle: "تقديرات التكاليف وتخطيط الميزانية",
    budgetHeaderSubtitle: "تفصيل واضح للتكاليف يشمل الإقامة، الوجبات المحلية، تذاكر الدخول، والمواصلات.",
    budgetTierLabel: "مستوى الميزانية:",
    totalEstTripCost: "إجمالي التكلفة التقديرية للرحلة",
    dailySpendAverage: "متوسط الإنفاق اليومي",
    perPersonEstimate: "التقدير لكل شخص",
    budgetStatus: "حالة الميزانية",
    onTrack: "ضمن الميزانية",
    includesAllExpenses: "يشمل السكن، الطعام، المواصلات والتذاكر",
    perTravelerTotal: "تقدير شامل لكل مسافر",
    alignedWithTier: "متوافق تماماً مع مستوى الراحة المحدد",
    categoryBreakdownTitle: "توزيع فئات النفقات",
    catLodging: "الإقامة الفندقية",
    catDining: "المطاعم المحلية",
    catTickets: "المعالم وتذاكر الدخول",
    catTransit: "المواصلات الداخلية",
    dailyCostBreakdownTitle: "تفصيل الإنفاق اليومي",
    thDay: "اليوم",
    thNeighborhood: "تجمع الحي",
    thMeals: "الوجبات والأكلات الشعبية",
    thTickets: "المعالم والتذاكر",
    thTransit: "المواصلات",
    thDailyTotal: "المجموع اليومي",
    customizeHeaderTitle: "استوديو التخصيص TripCraft",
    customizeHeaderSubtitle: "عدّل برنامج الرحلة ليلائم طاقة وميزانية مجموعتك.",
    paceControlTitle: "التحكم بالوتيرة والنمط",
    paceControlSubtitle: "اضبط كثافة الأنشطة لضمان راحة جميع المسافرين.",
    paceRelaxedName: "🌿 هادئ ومريح",
    paceRelaxedTag: "العائلات وكبار السن",
    paceRelaxedDesc: "انطلاق متأخر، نشاطان كحد أقصى يومياً، وفترات استراحة في المقاهي.",
    paceBalancedName: "⚖️ متوازن ومُنسّق",
    paceBalancedTag: "موصى به",
    paceBalancedDesc: "جولات صباحية ومسائية مع أوقات حرّة وأماكن متقاربة.",
    pacePackedName: "⚡ مكثّف ومغاطرة",
    pacePackedTag: "للمستكشفين النشطين",
    pacePackedDesc: "بداية مبكرة، 4-5 معالم رئيسية يومياً، واستكشاف كامل.",
    btnApplyPace: "تطبيق الوتيرة على الجدول",
    swapConsoleTitle: "تبديل الأنشطة أو المطاعم",
    swapConsoleSubtitle: "اختر أي فترة زمنية لعرض خيارات بديلة في نفس المنطقة.",
    labelTargetDay: "اختر اليوم للتعديل",
    labelTimeSlot: "الفترة الزمنية المراد تغييرها",
    slotMorning: "نشاط الصباح",
    slotLunch: "الغداء والمأكولات المحلية",
    slotAfternoon: "نشاط بعد الظهيرة",
    slotEvening: "جولة المساء والعشاء",
    labelCuratedAlternates: "الخيارات البديلة المختارة:",
    bookingGuidanceTitle: "دليل الحجز الرسمي",
    bookingGuidanceSubtitle: "تجنب عمولات الوسطاء بالحجز عبر المنصات الرسمية المباشرة.",
    packingHeaderTitle: "تجهيز الأمتعة الذكي",
    packingHeaderSubtitle: "قائمة مخصصة بناءً على الطقس، أعمار المسافرين، والأنشطة.",
    packed: "تم التجهيز",
    footerText: "نصمم رحلات مخصصة ومتكيفة مع الطقس حول العالم.",
    footerLangSupport: "يدعم جميع اللغات • تركيز على العائلات وسهولة الوصول",
    modalNewTripTitle: "تخطيط رحلة جديدة ومخصصة",
    formLabelDestination: "المدينة والدولة *",
    formLabelDuration: "المدة (بالأيام) *",
    formSectionTravelers: "من سيسافر؟ (عدد الأشخاص وفئات الأعمار)",
    formLabelAdults: "البالغون (18-64 سنة)",
    formLabelChildren: "الأطفال والمراهقون (0-17 سنة)",
    formLabelSeniors: "كبار السن (65+ سنة)",
    formLabelTripType: "نوع الرحلة *",
    typeFamily: "عائلية (مناسبة للأطفال)",
    typeCulture: "استكشاف ثقافي وتاريخي",
    typeRelaxation: "استجمام وطبيعة",
    typeCelebration: "احتفال وشهر عسل",
    typeAdventure: "مغامرة وسير في الطبيعة",
    formLabelBudgetPref: "الميزانية المفضلة *",
    budgetOptionEconomy: "اقتصادية (فنادق بسيطة، أكل شارع، مواصلات عامة)",
    budgetOptionModerate: "متوسطة / مريحة (فنادق عائلية، مطاعم جيدة)",
    budgetOptionLuxury: "فاخرة / ممتازة (فنادق 5 نجوم، مطاعم راقية، سيارة خاصة)",
    formLabelStartDate: "تاريخ بداية الرحلة",
    formLabelSpecialNotes: "ملاحظات خاصة / احتياجات سهولة الحركة",
    btnCancel: "إلغاء",
    btnGeneratePlan: "توليد خطة الرحلة المتكاملة",
    completed: "مكتمل",
    markCompleted: "تحديد كمكتمل",
    btnSwap: "تبديل",
    btnBook: "معلومات الحجز",
    btnSelectThis: "اختيار هذا",
    perNight: "/ ليلة",
    btnLogin: "تسجيل الدخول",
    btnRegister: "إنشاء حساب"
  },
  es: {
    tagline: "Planificador Personal de Viajes",
    selectTrip: "Seleccionar Viaje",
    navNewTrip: "Planificar Nuevo Viaje",
    labelTravelers: "Viajeros",
    labelStay: "Alojamiento Recomendado",
    labelBudget: "Gasto Diario Estimado",
    labelNeighborhood: "Barrio Actual",
    tabItinerary: "Itinerario Día a Día",
    tabStays: "Alojamientos Recomendados",
    tabBudget: "Presupuesto y Costos",
    tabCustomize: "Modificar y Personalizar",
    tabPacking: "Lista de Equipaje",
    btnAdjustPace: "Ajustar Ritmo",
    btnPrint: "Imprimir / PDF",
    labelNeighborhoodCluster: "Agrupación Geográfica del Barrio",
    transitOptimizedSubtext: "Actividades agrupadas en 1.2 km para minimizar traslados familiares.",
    labelWeatherAdaptation: "Plan de Adaptación al Clima",
    customizePlanTitle: "Personalizar Este Día",
    customizePlanSubtitle: "Cambia actividades, sustituye restaurantes o consulta enlaces de reserva.",
    actionSwapActivity: "Cambiar Actividad",
    actionSwapActivityDesc: "Descubre atracciones alternativas en este barrio",
    actionChangeRestaurant: "Cambiar Restaurante",
    actionChangeRestaurantDesc: "Elige opciones locales, vegetarianas o aptas para niños",
    actionAdjustPace: "Ajustar Ritmo del Día",
    actionAdjustPaceDesc: "Elige entre relajado, equilibrado o intenso",
    actionBookingGuide: "Guía y Enlaces de Reserva",
    actionBookingGuideDesc: "Pases oficiales, tarjetas de transporte y reservas directas",
    staysHeaderTitle: "Lugares Recomendados para Hospedarse",
    staysHeaderSubtitle: "Alojamientos seleccionados según tamaño del grupo, edades y presupuesto.",
    filterBy: "Filtrar por:",
    filterAll: "Todas las recomendaciones",
    filterFamilySuites: "Suites Familiares",
    filterAccessible: "Accesible para sillas y carriolas",
    filterCentral: "Cerca del Transporte",
    budgetHeaderTitle: "Estimación de Costos y Presupuesto",
    budgetHeaderSubtitle: "Desglose claro de hotel, gastronomía local, entradas y transporte.",
    budgetTierLabel: "Nivel de Presupuesto:",
    totalEstTripCost: "Costo Total Estimado del Viaje",
    dailySpendAverage: "Gasto Promedio Diario",
    perPersonEstimate: "Estimado por Persona",
    budgetStatus: "Estado del Presupuesto",
    onTrack: "En Orden",
    includesAllExpenses: "Incluye alojamiento, comidas, transporte y entradas",
    perTravelerTotal: "Estimado integral por viajero",
    alignedWithTier: "Alineado con tu nivel de confort seleccionado",
    categoryBreakdownTitle: "Distribución por Categorías",
    catLodging: "Alojamiento",
    catDining: "Comida Local",
    catTickets: "Atracciones y Entradas",
    catTransit: "Transporte Local",
    dailyCostBreakdownTitle: "Desglose de Gasto Diario",
    thDay: "Día",
    thNeighborhood: "Zona / Barrio",
    thMeals: "Comidas y Gastronomía",
    thTickets: "Atracciones y Boletos",
    thTransit: "Transporte",
    thDailyTotal: "Total Diario",
    customizeHeaderTitle: "Estudio de Personalización TripCraft",
    customizeHeaderSubtitle: "Adapta el itinerario a la energía y preferencias de tu grupo.",
    paceControlTitle: "Ritmo y Frecuencia",
    paceControlSubtitle: "Ajusta la densidad de actividades para el bienestar de todos.",
    paceRelaxedName: "🌿 Relajado y sin prisas",
    paceRelaxedTag: "Familias y Mayores",
    paceRelaxedDesc: "Mañanas tardías, máximo 2 actividades diarias y descansos en cafés.",
    paceBalancedName: "⚖️ Equilibrado y Curado",
    paceBalancedTag: "Recomendado",
    paceBalancedDesc: "Exploración matutina y vespertina con tardes flexibles y cercanía.",
    pacePackedName: "⚡ Intenso y Dinámico",
    pacePackedTag: "Exploradores Activos",
    pacePackedDesc: "Comienzo temprano, 4-5 visitas principales y máxima aventura.",
    btnApplyPace: "Aplicar Ritmo al Itinerario",
    swapConsoleTitle: "Cambiar Actividades o Restaurantes",
    swapConsoleSubtitle: "Selecciona cualquier horario para ver alternativas en la misma zona.",
    labelTargetDay: "Seleccionar Día a Modificar",
    labelTimeSlot: "Horario a Cambiar",
    slotMorning: "Actividad Matutina",
    slotLunch: "Almuerzo y Comida Local",
    slotAfternoon: "Actividad de Tarde",
    slotEvening: "Paseo Nocturno y Cena",
    labelCuratedAlternates: "Alternativas Seleccionadas:",
    bookingGuidanceTitle: "Guía de Reserva Oficial",
    bookingGuidanceSubtitle: "Evita sobreprecios de intermediarios con enlaces oficiales.",
    packingHeaderTitle: "Equipaje Inteligente",
    packingHeaderSubtitle: "Lista adaptada al clima, edades del grupo y actividades.",
    packed: "Empacado",
    footerText: "Diseñando viajes personalizados y adaptados al clima en todo el mundo.",
    footerLangSupport: "Compatible con todos los idiomas • Enfoque familiar y accesible",
    modalNewTripTitle: "Planificar un Nuevo Viaje Personalizado",
    formLabelDestination: "Ciudad y País de Destino *",
    formLabelDuration: "Duración (Días) *",
    formSectionTravelers: "¿Quiénes viajan? (Cantidad y edades)",
    formLabelAdults: "Adultos (18-64 años)",
    formLabelChildren: "Niños / Jóvenes (0-17 años)",
    formLabelSeniors: "Adultos Mayores (65+ años)",
    formLabelTripType: "Tipo de Visita *",
    typeFamily: "Vacaciones Familiares (Apto para niños)",
    typeCulture: "Exploración Cultural e Historia",
    typeRelaxation: "Relajación y Naturaleza",
    typeCelebration: "Celebración y Luna de Miel",
    typeAdventure: "Aventura y Senderismo",
    formLabelBudgetPref: "Preferencia de Presupuesto *",
    budgetOptionEconomy: "Económico (Hostales, comida callejera, metro)",
    budgetOptionModerate: "Moderado / Confort (Hoteles familiares, buenos restaurantes)",
    budgetOptionLuxury: "Lujo / Premium (Hoteles 5 estrellas, alta cocina, traslados)",
    formLabelStartDate: "Fecha de Inicio",
    formLabelSpecialNotes: "Preferencias especiales / Accesibilidad",
    btnCancel: "Cancelar",
    btnGeneratePlan: "Generar Plan Completo",
    completed: "Completado",
    markCompleted: "Marcar Listo",
    btnSwap: "Cambiar",
    btnBook: "Info Reserva",
    btnSelectThis: "Elegir este",
    perNight: "/ noche",
    btnLogin: "Iniciar Sesión",
    btnRegister: "Registrarse"
  },
  fr: {
    tagline: "Planificateur de Voyage Personnel",
    selectTrip: "Sélectionner le Voyage",
    navNewTrip: "Nouveau Voyage",
    labelTravelers: "Voyageurs",
    labelStay: "Hébergement Recommandé",
    labelBudget: "Dépense Quotidienne Estimée",
    labelNeighborhood: "Quartier Actuel",
    tabItinerary: "Itinéraire Jour par Jour",
    tabStays: "Hébergements Recommandés",
    tabBudget: "Estimations & Budget",
    tabCustomize: "Modifier & Personnaliser",
    tabPacking: "Liste de Bagages",
    btnAdjustPace: "Ajuster le Rythme",
    btnPrint: "Imprimer / PDF",
    labelNeighborhoodCluster: "Regroupement Géographique du Quartier",
    transitOptimizedSubtext: "Activités regroupées à moins de 1,2 km pour limiter les trajets en famille.",
    labelWeatherAdaptation: "Plan d'Adaptation Météorologique",
    customizePlanTitle: "Personnaliser Cette Journée",
    customizePlanSubtitle: "Changez une activité, remplacez un restaurant ou consultez les liens de réservation.",
    actionSwapActivity: "Remplacer une Activité",
    actionSwapActivityDesc: "Consultez les alternatives dans le même quartier",
    actionChangeRestaurant: "Changer de Restaurant",
    actionChangeRestaurantDesc: "Choisissez un restaurant local adapté aux enfants ou végétarien",
    actionAdjustPace: "Ajuster le Rythme",
    actionAdjustPaceDesc: "Passez d'un rythme détendu à équilibré ou intense",
    actionBookingGuide: "Guide & Liens de Réservation",
    actionBookingGuideDesc: "Pass officiels, cartes de transport et réservations directes",
    staysHeaderTitle: "Hébergements Recommandés",
    staysHeaderSubtitle: "Logements adaptés à la taille de votre groupe, aux âges et au budget.",
    filterBy: "Filtrer par :",
    filterAll: "Toutes les recommandations",
    filterFamilySuites: "Suites Familiales",
    filterAccessible: "Poussettes & Fauteuils Roulants",
    filterCentral: "Proche des Transports",
    budgetHeaderTitle: "Estimations des Coûts & Budget",
    budgetHeaderSubtitle: "Détail clair des coûts d'hébergement, repas locaux, billets et transports.",
    budgetTierLabel: "Niveau de Budget :",
    totalEstTripCost: "Coût Total Estimé du Voyage",
    dailySpendAverage: "Dépense Moyenne Quotidienne",
    perPersonEstimate: "Estimation par Personne",
    budgetStatus: "Santé du Budget",
    onTrack: "En Bonne Voie",
    includesAllExpenses: "Comprend hébergement, repas, transports et billets",
    perTravelerTotal: "Estimation complète par voyageur",
    alignedWithTier: "Conforme à votre niveau de confort choisi",
    categoryBreakdownTitle: "Répartition par Catégorie",
    catLodging: "Hébergement",
    catDining: "Restauration Locale",
    catTickets: "Attractions & Visites",
    catTransit: "Transports Locaux",
    dailyCostBreakdownTitle: "Détail des Dépenses par Jour",
    thDay: "Jour",
    thNeighborhood: "Quartier",
    thMeals: "Repas & Spécialités",
    thTickets: "Attractions & Billets",
    thTransit: "Transports",
    thDailyTotal: "Total Journalier",
    customizeHeaderTitle: "Studio de Personnalisation TripCraft",
    customizeHeaderSubtitle: "Ajustez le voyage selon l'énergie de votre famille et vos envies.",
    paceControlTitle: "Rythme & Cadence Quotidienne",
    paceControlSubtitle: "Adaptez la densité des visites au bien-être de chacun.",
    paceRelaxedName: "🌿 Détendu & Serein",
    paceRelaxedTag: "Famille & Aînés",
    paceRelaxedDesc: "Matinées calmes, 2 visites par jour maximum et pauses gourmandes.",
    paceBalancedName: "⚖️ Équilibré & Soigné",
    paceBalancedTag: "Recommandé",
    paceBalancedDesc: "Exploration matin et après-midi avec soirées libres et visites proches.",
    pacePackedName: "⚡ Intense & Actif",
    pacePackedTag: "Explorateurs Énergiques",
    pacePackedDesc: "Départ matinal, 4 à 5 visites majeures par jour et découverte maximale.",
    btnApplyPace: "Appliquer le Rythme",
    swapConsoleTitle: "Remplacer Activités ou Restaurants",
    swapConsoleSubtitle: "Sélectionnez un créneau pour voir des alternatives immédiates dans le quartier.",
    labelTargetDay: "Sélectionner le Jour",
    labelTimeSlot: "Créneau à Remplacer",
    slotMorning: "Activité du Matin",
    slotLunch: "Déjeuner & Spécialités",
    slotAfternoon: "Activité de l'Après-midi",
    slotEvening: "Soirée & Dîner",
    labelCuratedAlternates: "Alternatives Recommandées :",
    bookingGuidanceTitle: "Conseils & Liens de Réservation Directe",
    bookingGuidanceSubtitle: "Évitez les surcoûts des intermédiaires avec les portails officiels.",
    packingHeaderTitle: "Préparation des Bagages Intelligente",
    packingHeaderSubtitle: "Liste adaptée à la météo, à l'âge des voyageurs et aux visites prévues.",
    packed: "Préparé",
    footerText: "Création de voyages personnalisés et adaptés à la météo dans le monde entier.",
    footerLangSupport: "Compatible avec toutes les langues • Axé sur la famille et l'accessibilité",
    modalNewTripTitle: "Créer un Nouveau Voyage Personnalisé",
    formLabelDestination: "Ville & Pays de Destination *",
    formLabelDuration: "Durée (Jours) *",
    formSectionTravelers: "Qui voyage ? (Composition du groupe & âges)",
    formLabelAdults: "Adultes (18-64 ans)",
    formLabelChildren: "Enfants / Ados (0-17 ans)",
    formLabelSeniors: "Seniors (65+ ans)",
    formLabelTripType: "Type de Séjour *",
    typeFamily: "Vacances en Famille (Adapté aux enfants)",
    typeCulture: "Découverte Culturelle & Histoire",
    typeRelaxation: "Détente, Paysages & Bien-être",
    typeCelebration: "Célébration & Voyage de Noces",
    typeAdventure: "Aventure & Randonnée",
    formLabelBudgetPref: "Préférence Budgétaire *",
    budgetOptionEconomy: "Économique (Auberges, cuisine de rue, métro)",
    budgetOptionModerate: "Modéré / Confort (Hôtels familiaux, bons restaurants)",
    budgetOptionLuxury: "Luxe / Prestige (Hôtels 5 étoiles, gastronomie, transferts)",
    formLabelStartDate: "Date de Début",
    formLabelSpecialNotes: "Préférences particulières / Accessibilité",
    btnCancel: "Annuler",
    btnGeneratePlan: "Générer le Plan Complet",
    completed: "Effectué",
    markCompleted: "Marquer comme fait",
    btnSwap: "Remplacer",
    btnBook: "Info Réservation",
    btnSelectThis: "Choisir cet élément",
    perNight: "/ nuit",
    btnLogin: "Connexion",
    btnRegister: "S'inscrire"
  },
  ja: {
    tagline: "パーソナル旅行プランナー",
    selectTrip: "旅行を選択",
    navNewTrip: "新しい旅を計画",
    labelTravelers: "旅行者",
    labelStay: "おすすめの宿泊先",
    labelBudget: "1日の目安支出",
    labelNeighborhood: "現在のエリア",
    tabItinerary: "日別旅程表",
    tabStays: "おすすめ宿泊先",
    tabBudget: "予算と費用見積もり",
    tabCustomize: "プランの変更・調整",
    tabPacking: "持ち物チェックリスト",
    btnAdjustPace: "ペース調整",
    btnPrint: "印刷 / PDF",
    labelNeighborhoodCluster: "地域・エリアグループ",
    transitOptimizedSubtext: "徒歩や移動時間を最小限に抑えるため、半径1.2km以内で活動をまとめています。",
    labelWeatherAdaptation: "気候・天候適応プラン",
    customizePlanTitle: "この日のプランをカスタマイズ",
    customizePlanSubtitle: "観光スポットの入れ替え、食事場所の変更、ペース調整、直接予約案内を簡単に行えます。",
    actionSwapActivity: "アクティビティの入れ替え",
    actionSwapActivityDesc: "同じエリア内のおすすめ観光スポットから選択",
    actionChangeRestaurant: "食事処の変更",
    actionChangeRestaurantDesc: "お子様連れ、ベジタリアン、郷土料理店から選択",
    actionAdjustPace: "旅のペースを調整",
    actionAdjustPaceDesc: "ゆったり、バランス、アクティブから選択",
    actionBookingGuide: "公式予約案内＆リンク",
    actionBookingGuideDesc: "公式チケット、交通ICカード、直接予約サイト",
    staysHeaderTitle: "おすすめの宿泊施設",
    staysHeaderSubtitle: "人数、年齢層、バリアフリー対応、ご予算に合わせた厳選ホテルです。",
    filterBy: "絞り込み:",
    filterAll: "すべてのおすすめ",
    filterFamilySuites: "ファミリールーム",
    filterAccessible: "バリアフリー・ベビーカー対応",
    filterCentral: "駅近・交通至便",
    budgetHeaderTitle: "費用見積もりと予算計画",
    budgetHeaderSubtitle: "宿泊費、郷土料理、観光入場料、地域交通費の明確な内訳です。",
    budgetTierLabel: "予算ランク:",
    totalEstTripCost: "推定旅行総費用",
    dailySpendAverage: "1日の平均支出",
    perPersonEstimate: "1人あたりの見積もり",
    budgetStatus: "予算状況",
    onTrack: "順調（予算内）",
    includesAllExpenses: "宿泊・食事・交通・入場料を含む",
    perTravelerTotal: "旅行者1人あたりの総計目安",
    alignedWithTier: "選択された快適ランクに合致しています",
    categoryBreakdownTitle: "支出カテゴリ内訳",
    catLodging: "宿泊費",
    catDining: "郷土料理・食事",
    catTickets: "観光・入場料",
    catTransit: "地域交通費",
    dailyCostBreakdownTitle: "日別の費用内訳",
    thDay: "日程",
    thNeighborhood: "エリア",
    thMeals: "食事・ご当地グルメ",
    thTickets: "観光・体験",
    thTransit: "交通費",
    thDailyTotal: "日計",
    customizeHeaderTitle: "TripCraft カスタマイズスタジオ",
    customizeHeaderSubtitle: "旅行者の体力、食事の好み、旅行テンポに合わせて旅程を自在に調整できます。",
    paceControlTitle: "旅のペースとテンポ",
    paceControlSubtitle: "ご家族の体力や旅行スタイルに合わせて予定の密度を調整します。",
    paceRelaxedName: "🌿 ゆったり・のんびり",
    paceRelaxedTag: "ファミリー＆シニア向け",
    paceRelaxedDesc: "朝はゆっくり出発。1日最大2箇所の見学で、カフェ休憩を多めに取ります。",
    paceBalancedName: "⚖️ バランス重視",
    paceBalancedTag: "おすすめ",
    paceBalancedDesc: "午前と午後にバランスよく観光し、夜は自由度の高いスケジュールです。",
    pacePackedName: "⚡ アクティブ満喫",
    pacePackedTag: "アクティブ派向け",
    pacePackedDesc: "朝早くから夜まで、主要スポットを巡り尽くす充実の旅程です。",
    btnApplyPace: "ペースを旅程に適用",
    swapConsoleTitle: "観光地や飲食店の入れ替え",
    swapConsoleSubtitle: "変更したい時間帯を選ぶと、近隣の魅力的な代替案が提案されます。",
    labelTargetDay: "変更する日程を選択",
    labelTimeSlot: "変更する時間帯",
    slotMorning: "午前の観光",
    slotLunch: "昼食・ご当地グルメ",
    slotAfternoon: "午後の観光",
    slotEvening: "夜の観光＆夕食",
    labelCuratedAlternates: "おすすめの代替候補:",
    bookingGuidanceTitle: "公式予約案内＆リンク",
    bookingGuidanceSubtitle: "公式予約ポータルや交通パスを利用して、安心・お得に予約できます。",
    packingHeaderTitle: "スマート持ち物チェックリスト",
    packingHeaderSubtitle: "現地の天候、旅行者の年齢層、訪問先に合わせた安心リストです。",
    packed: "準備済み",
    footerText: "世界中の旅行者に寄り添う、天候適応型の旅行計画をデザインします。",
    footerLangSupport: "全言語対応 • ファミリー＆アクセシビリティ対応",
    modalNewTripTitle: "新しい旅行プランを作成",
    formLabelDestination: "旅行先の都市・国 *",
    formLabelDuration: "旅行日数 *",
    formSectionTravelers: "旅行者の人数と内訳（年齢層）",
    formLabelAdults: "大人 (18-64歳)",
    formLabelChildren: "子供・若者 (0-17歳)",
    formLabelSeniors: "シニア (65歳以上)",
    formLabelTripType: "旅行の目的 *",
    typeFamily: "家族旅行 (子供も楽しめるバランス型)",
    typeCulture: "歴史・文化探訪",
    typeRelaxation: "リゾート・温泉・癒やし",
    typeCelebration: "記念日・ハネムーン",
    typeAdventure: "自然体験・アクティビティ",
    formLabelBudgetPref: "予算設定 *",
    budgetOptionEconomy: "エコノミー（手頃な宿、ローカル食堂、公共交通）",
    budgetOptionModerate: "スタンダード・快適（快適ホテル、名物料理、周遊パス）",
    budgetOptionLuxury: "プレミアム・高級（高級ホテル、特別ディナー、専用車）",
    formLabelStartDate: "出発日",
    formLabelSpecialNotes: "特記事項 / バリアフリーのご要望",
    btnCancel: "キャンセル",
    btnGeneratePlan: "旅行プランを自動生成",
    completed: "完了",
    markCompleted: "完了にする",
    btnSwap: "変更する",
    btnBook: "予約案内",
    btnSelectThis: "これに変更",
    perNight: "/ 泊",
    btnLogin: "ログイン",
    btnRegister: "新規登録"
  },
  de: {
    tagline: "Persönlicher Reiseplaner",
    selectTrip: "Reise Auswählen",
    navNewTrip: "Neue Reise Planen",
    labelTravelers: "Reisende",
    labelStay: "Empfohlene Unterkunft",
    labelBudget: "Geschätzte Tagesausgaben",
    labelNeighborhood: "Aktueller Stadtteil",
    tabItinerary: "Tagesprogramm",
    tabStays: "Empfohlene Unterkünfte",
    tabBudget: "Kosten & Budget",
    tabCustomize: "Anpassen & Ändern",
    tabPacking: "Packliste",
    btnAdjustPace: "Tempo Anpassen",
    btnPrint: "Drucken / PDF",
    labelNeighborhoodCluster: "Geografischer Stadtteil-Cluster",
    transitOptimizedSubtext: "Aktivitäten im Umkreis von 1,2 km gebündelt, um Gehzeiten für Familien zu minimieren.",
    labelWeatherAdaptation: "Wetteranpassungsplan",
    customizePlanTitle: "Diesen Tag Anpassen",
    customizePlanSubtitle: "Tauschen Sie Aktivitäten oder Restaurants unkompliziert aus und erhalten Sie Buchungslinks.",
    actionSwapActivity: "Aktivität Tauschen",
    actionSwapActivityDesc: "Alternative Highlights im selben Viertel entdecken",
    actionChangeRestaurant: "Restaurant Ändern",
    actionChangeRestaurantDesc: "Lokale Lokale für Familien oder Vegetarier wählen",
    actionAdjustPace: "Tages-Tempo Ändern",
    actionAdjustPaceDesc: "Wählen Sie zwischen entspannt, ausgewogen und aktiv",
    actionBookingGuide: "Buchungshilfen & Links",
    actionBookingGuideDesc: "Offizielle Pässe, Nahverkehrskarten und Direktbuchungen",
    staysHeaderTitle: "Empfohlene Unterkünfte",
    staysHeaderSubtitle: "Ausgewählte Hotels passend zu Gruppengröße, Alter und Budget.",
    filterBy: "Filtern nach:",
    filterAll: "Alle Empfehlungen",
    filterFamilySuites: "Familiensuiten",
    filterAccessible: "Barrierefrei / Kinderwagen",
    filterCentral: "Verkehrsgünstig",
    budgetHeaderTitle: "Kostenschätzung & Budget",
    budgetHeaderSubtitle: "Transparente Kostenaufstellung für Hotel, Verpflegung, Eintritte und Nahverkehr.",
    budgetTierLabel: "Budget-Klasse:",
    totalEstTripCost: "Geschätzte Gesamtkosten",
    dailySpendAverage: "Durchschnittliche Tagesausgaben",
    perPersonEstimate: "Schätzung pro Person",
    budgetStatus: "Budget-Status",
    onTrack: "Im Budget",
    includesAllExpenses: "Inklusive Hotel, Essen, Nahverkehr und Eintrittskarten",
    perTravelerTotal: "Gesamtschätzung pro Reisenden",
    alignedWithTier: "Entspricht Ihrer gewählten Komfortklasse",
    categoryBreakdownTitle: "Ausgaben nach Kategorien",
    catLodging: "Unterkunft",
    catDining: "Lokale Küche",
    catTickets: "Attraktionen & Eintritte",
    catTransit: "Nahverkehr",
    dailyCostBreakdownTitle: "Tägliche Kostenaufstellung",
    thDay: "Tag",
    thNeighborhood: "Stadtviertel",
    thMeals: "Mahlzeiten & Spezialitäten",
    thTickets: "Sehenswürdigkeiten",
    thTransit: "Transport",
    thDailyTotal: "Tagessumme",
    customizeHeaderTitle: "TripCraft Studio für Anpassungen",
    customizeHeaderSubtitle: "Passen Sie die Reise flexibel an das Wohlbefinden Ihrer Reisegruppe an.",
    paceControlTitle: "Tages-Geschwindigkeit & Rhythmus",
    paceControlSubtitle: "Wählen Sie die Intensität für ein entspanntes Reiseerlebnis.",
    paceRelaxedName: "🌿 Entspannt & Gemütlich",
    paceRelaxedTag: "Familien & Senioren",
    paceRelaxedDesc: "Späterer Start, maximal 2 Programmpunkte pro Tag und viel Zeit für Cafés.",
    paceBalancedName: "⚖️ Ausgewogen & Kuratiert",
    paceBalancedTag: "Empfohlen",
    paceBalancedDesc: "Gute Balance zwischen Vormittags- und Nachmittagszielen mit kurzen Wegen.",
    pacePackedName: "⚡ Aktiv & Erlebnisreich",
    pacePackedTag: "Aktive Entdecker",
    pacePackedDesc: "Früher Start, 4-5 Höhepunkte täglich und maximale Entdeckungen.",
    btnApplyPace: "Tempo Übernehmen",
    swapConsoleTitle: "Aktivitäten oder Lokale Tauschen",
    swapConsoleSubtitle: "Wählen Sie ein Zeitfenster für sofortige Vorschläge im selben Viertel.",
    labelTargetDay: "Tag Auswählen",
    labelTimeSlot: "Zeitfenster zum Tauschen",
    slotMorning: "Vormittags-Aktivität",
    slotLunch: "Mittagessen & Lokale Küche",
    slotAfternoon: "Nachmittags-Aktivität",
    slotEvening: "Abendprogramm & Dinner",
    labelCuratedAlternates: "Empfohlene Alternativen:",
    bookingGuidanceTitle: "Offizielle Buchungsanleitungen",
    bookingGuidanceSubtitle: "Sparen Sie Zwischenhändler-Gebühren durch offizielle Portale.",
    packingHeaderTitle: "Intelligente Packliste",
    packingHeaderSubtitle: "Abgestimmt auf Wetter, Altersgruppen und geplante Aktivitäten.",
    packed: "Gepackt",
    footerText: "Personalisierte und wetterangepasste Reiseplanung weltweit.",
    footerLangSupport: "Kompatibel mit allen Sprachen • Fokus auf Familien & Barrierefreiheit",
    modalNewTripTitle: "Neue Reise Planen",
    formLabelDestination: "Zielstadt & Land *",
    formLabelDuration: "Dauer (Tage) *",
    formSectionTravelers: "Wer reist mit? (Personen & Altersgruppen)",
    formLabelAdults: "Erwachsene (18-64 J.)",
    formLabelChildren: "Kinder / Jugendliche (0-17 J.)",
    formLabelSeniors: "Senioren (65+ J.)",
    formLabelTripType: "Art der Reise *",
    typeFamily: "Familienurlaub (Kinderfreundlich & ausgewogen)",
    typeCulture: "Kultur & Geschichte",
    typeRelaxation: "Erholung & Natur",
    typeCelebration: "Feier & Flitterwochen",
    typeAdventure: "Abenteuer & Wandern",
    formLabelBudgetPref: "Budget-Präferenz *",
    budgetOptionEconomy: "Günstig (Einfache Hotels, Streetfood, ÖPNV)",
    budgetOptionModerate: "Mittel / Komfortabel (Familienhotels, gute Lokale)",
    budgetOptionLuxury: "Gehoben / Luxus (5-Sterne, Gourmetküche, Privattransfers)",
    formLabelStartDate: "Reisebeginn",
    formLabelSpecialNotes: "Besondere Wünsche / Barrierefreiheit",
    btnCancel: "Abbrechen",
    btnGeneratePlan: "Kompletten Reiseplan Erstellen",
    completed: "Erledigt",
    markCompleted: "Als erledigt markieren",
    btnSwap: "Tauschen",
    btnBook: "Buchungs-Info",
    btnSelectThis: "Auswählen",
    perNight: "/ Nacht",
    btnLogin: "Anmelden",
    btnRegister: "Registrieren"
  }
};